### ISSUE TITLE
Issue: Need help with MongoDB structure

### ISSUE THREAD

**Issue by irwintsay** [irwintsay/VGDB#1]
I'm not sure how I should organize my Mongo database which will store User accounts and search data.

**Comment by CentroDL** [comment]
what's your current approach?

**Comment by irwintsay** [comment]
I'm pretty sure I'm going to implement user accounts and store the searches each User makes. Each search object would contain:

queryString
count
time/date

But I also want to have a stats page that shows all search data regardless of user and so I'm wondering if I really need to associate Searches with a User or just separate collections for Users and Searches.

**Comment by CentroDL** [comment]
if you're doing it the mongo way just have it under the user. having a separate search collection with a user id would result in two queries and a full table scan that will slow down tremendously as your app accumulates searches

**Comment by CentroDL** [comment]
document scan*

**Comment by irwintsay** [comment]
Let's say that I want to have access to all Searches from all Users so I can easily display stats like, most popular searches, or most recent searches. Is it worth the resource cost of redundantly storing Searches in it's own collection so that it's easy to grab all of them, versus only storing Searches nested within Users and having to query all Users to get all Searches every time I want access to all Searches?

**Comment by CentroDL** [comment]
for your life, its better :)

so go with the separate search collection with the user_id

**Comment by irwintsay** [comment]
lol, ok thanks
