### ISSUE TITLE
Issue: "E11000 duplicate key error collection: vgdb.users index: searches.queryString_1 dup key: { : null }"

### ISSUE THREAD

**Issue by irwintsay** [irwintsay/VGDB#2]
I'm getting this error when I try to create a second User in my Mongo database. It's an issue with my array of nested schema.

**Comment by ajhofferber** [comment]
hey. do you have any "unique" validators in your schema?

**Comment by irwintsay** [comment]
I did, but I took them out of the schema and still got that error. It's ok though, Rafa made a suggestion to split up the schemas into their own collections so I no longer have that issue.
