### ISSUE TITLE
Issue: Need help with routing my views with Angular

### ISSUE THREAD

**Issue by irwintsay** [irwintsay/VGDB#5]
Not sure how I should structure my routes to views

**Comment by irwintsay** [comment]
Ok so I need help figuring out how to get Angular partials working with controllers in separate files. Please help!

**Comment by irwintsay** [comment]
Sorry I was wrong, I'm still not able to correctly link my Angular Controllers.

**Comment by rapala61** [comment]
pushed your latest code to github.

**Comment by irwintsay** [comment]
I just pushed up my latest build. I'm currently working in **branch: feature-rework_angular_module**

**Comment by irwintsay** [comment]
I fixed the issue. One of my controllers was failing to inject because I forgot to link angular-cookie.js in my new html file. Ughhhhh.
